
#include "main.h"
Adafruit_SSD1306 display(128, 64, &Wire, OLED_RST_PIN);

// OLED Animation: walk
// Code auto-generated by https://wokwi.com/animator, graphics by icons8.com


void setup() {
  display.begin(SSD1306_SWITCHCAPVCC, SCREEN_I2C_ADDR);
}

int frame = 0;
void loop() {
  display.clearDisplay();
  display.drawBitmap(32, 0, frames[frame], FRAME_WIDTH, FRAME_HEIGHT, 1);
  display.display();
  frame = (frame + 1) % FRAME_COUNT;
}